export const GET_LOGIN = 'GET_LOGIN';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_ERROR = 'GET_LOGIN_ERROR';

export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';

export const GET_PROJECT_BYID = 'GET_PROJECT_BYID';
export const GET_PROJECT_BYID_SUCCESS = 'GET_PROJECT_BYID_SUCCESS';
export const GET_PROJECT_BYID_ERROR = 'GET_PROJECT_BYID_ERROR';